-- ⚠️ AMARAN: SKRIP INI AKAN MEMADAM DATA DI TABLE PREMISES DAN VISITS LAMA
-- Pastikan anda telah backup data jika perlu.

-- 1. Drop Old Tables (Cascade will remove visits too)
drop table if exists public.visits cascade;
drop table if exists public.premises cascade;

-- 2. Create New Tables
-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Table: Premises
create table public.premises (
    uuid uuid primary key default uuid_generate_v4(),
    nama_kedai text not null,
    no_lot text not null,
    status_perkeso text not null default 'Belum Daftar',
    gps text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table: Visits
create table public.visits (
    id bigint generated by default as identity primary key,
    premis_id uuid references public.premises(uuid) on delete cascade not null,
    inspector_id uuid references auth.users(id) not null,
    status text not null,
    catatan text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable RLS
alter table public.premises enable row level security;
alter table public.visits enable row level security;

-- 4. Policies
create policy "Public premises are viewable by everyone"
on public.premises for select to public using (true);

create policy "Inspectors can insert premises"
on public.premises for insert to authenticated with check (true);

create policy "Inspectors can view visits"
on public.visits for select to authenticated using (true);

create policy "Inspectors can insert visits"
on public.visits for insert to authenticated with check (auth.uid() = inspector_id);
