-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Table: Premises
create table if not exists public.premises (
    uuid uuid primary key default uuid_generate_v4(),
    nama_kedai text not null,
    no_lot text not null,
    status_perkeso text not null default 'Belum Daftar',
    gps text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table: Visits
create table if not exists public.visits (
    id bigint generated by default as identity primary key,
    premis_id uuid references public.premises(uuid) on delete cascade not null,
    inspector_id uuid references auth.users(id) not null,
    status text not null,
    catatan text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.premises enable row level security;
alter table public.visits enable row level security;

-- Policies for Premises
-- Allow public read (for scanning)
create policy "Public premises are viewable by everyone"
on public.premises for select
to public
using (true);

-- Allow authenticated (inspectors) to insert
create policy "Inspectors can insert premises"
on public.premises for insert
to authenticated
with check (true);

-- Policies for Visits
-- Allow authenticated (inspectors) to read visits
create policy "Inspectors can view visits"
on public.visits for select
to authenticated
using (true);

-- Allow authenticated (inspectors) to insert visits
create policy "Inspectors can insert visits"
on public.visits for insert
to authenticated
with check (auth.uid() = inspector_id);
