-- ⚠️ AMARAN: SKRIP INI AKAN MEMADAM SEMUA DATA DAN CREATE SCRIPTS BARU
-- Pastikan anda telah backup data jika perlu.

-- 1. Reset Database (Drop existing tables)
drop table if exists public.visits cascade;
drop table if exists public.premises cascade;

-- 2. Create Extensions
create extension if not exists "uuid-ossp";

-- 3. Create Tables

-- Table: Premises
create table public.premises (
    uuid uuid primary key default uuid_generate_v4(),
    nama_kedai text not null,
    no_lot text not null,
    status_perkeso text not null default 'Belum Daftar'
        check (status_perkeso in ('Belum Daftar', 'Sudah Daftar', 'Ragu-ragu')),
    kod_majikan text, -- Added missing column
    gps text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    constraint kod_majikan_required
        check (status_perkeso <> 'Sudah Daftar' or kod_majikan is not null)
);

-- Table: Visits
create table public.visits (
    id bigint generated by default as identity primary key,
    premis_id uuid references public.premises(uuid) on delete cascade not null,
    inspector_id uuid references auth.users(id) not null,
    status text not null
        check (status in ('Patuh', 'Kompoun', 'Lawat Semula')), -- 'Patuh', 'Kompoun', 'Lawat Semula'
    catatan text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3b. Indexes
create index if not exists visits_premis_id_idx on public.visits (premis_id);

-- 4. Enable Row Level Security (RLS)
alter table public.premises enable row level security;
alter table public.visits enable row level security;

-- 5. RLS Policies

-- Premises Policies
-- Allow public to read premises (needed for scanning QR codes without login initially)
create policy "Public premises are viewable by everyone"
on public.premises for select
to public
using (true);

-- Allow authenticated inspectors to create new premises
create policy "Inspectors can insert premises"
on public.premises for insert
to authenticated
with check (true);

-- Allow public to create new premises (register flow without login)
create policy "Public can insert premises"
on public.premises for insert
to public
with check (true);

-- Allow authenticated inspectors to update premises (status/kod_majikan)
create policy "Inspectors can update premises"
on public.premises for update
to authenticated
using (true)
with check (true);

-- Visits Policies
-- Allow authenticated inspectors to view visits
-- Note: Currently allows viewing ALL visits. Change to `auth.uid() = inspector_id` if privacy is needed.
create policy "Inspectors can view visits"
on public.visits for select
to authenticated
using (true);

-- Allow authenticated inspectors to insert visits (must be their own)
create policy "Inspectors can insert visits"
on public.visits for insert
to authenticated
with check (auth.uid() = inspector_id);

-- 6. Comments
comment on column public.premises.kod_majikan is 'Employer Code (Kod Majikan) for registered premises';
